// ══════════════════════════════════════════════════════════════
// PM2 Ecosystem — DarCloud Autonomous Services
// Auto-restart, log rotation, health monitoring
// ══════════════════════════════════════════════════════════════
module.exports = {
  apps: [
    // ── Wrangler Dev Server (API) ─────────────────────────────
    {
      name: "darcloud-api",
      cwd: "/workspaces/quranchain1",
      script: "npx",
      args: "wrangler dev --port 8787",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 3000,
      min_uptime: 10000,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
      // Log management
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/api-error.log",
      out_file: "/workspaces/quranchain1/logs/api-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── Discord Bot ───────────────────────────────────────────
    {
      name: "darcloud-bot",
      cwd: "/workspaces/quranchain1/discord-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "bot.log", "*.log"],
      // Wait for API to be ready before bot starts
      wait_ready: false,
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/bot-error.log",
      out_file: "/workspaces/quranchain1/logs/bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── QuranChain Blockchain Bot ────────────────────────────
    {
      name: "quranchain-bot",
      cwd: "/workspaces/quranchain1/quranchain-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js", "blockchain.js", "games.js", "database.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.db", "*.log"],
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/quranchain-error.log",
      out_file: "/workspaces/quranchain1/logs/quranchain-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── Health Watchdog ───────────────────────────────────────
    {
      name: "darcloud-watchdog",
      cwd: "/workspaces/quranchain1",
      script: "discord-bot/watchdog.js",
      autorestart: true,
      max_restarts: 50,
      restart_delay: 10000,
      min_uptime: 5000,
      env: {
        NODE_ENV: "production",
        API_BASE: "http://localhost:8787",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/watchdog-error.log",
      out_file: "/workspaces/quranchain1/logs/watchdog-out.log",
      merge_logs: true,
      max_size: "5M",
      retain: 3,
    },

    // ── FungiMesh Bot ─────────────────────────────────────────
    {
      name: "fungimesh-bot",
      cwd: "/workspaces/quranchain1/fungimesh-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/fungimesh-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/fungimesh-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── MeshTalk OS Bot ───────────────────────────────────────
    {
      name: "meshtalk-bot",
      cwd: "/workspaces/quranchain1/meshtalk-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/meshtalk-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/meshtalk-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── AI Fleet Bot ──────────────────────────────────────────
    {
      name: "aifleet-bot",
      cwd: "/workspaces/quranchain1/aifleet-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/aifleet-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/aifleet-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── Halal Wealth Club Bot ─────────────────────────────────
    {
      name: "hwc-bot",
      cwd: "/workspaces/quranchain1/hwc-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/hwc-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/hwc-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarLaw Legal AI Bot ───────────────────────────────────
    {
      name: "darlaw-bot",
      cwd: "/workspaces/quranchain1/darlaw-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darlaw-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darlaw-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarPay Revenue Bot ────────────────────────────────────
    {
      name: "darpay-bot",
      cwd: "/workspaces/quranchain1/darpay-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darpay-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darpay-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── Dar Al-Nas Bank Bot ──────────────────────────────────
    {
      name: "darnas-bot",
      cwd: "/workspaces/quranchain1/darnas-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darnas-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darnas-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarHealth Bot ─────────────────────────────────────────
    {
      name: "darhealth-bot",
      cwd: "/workspaces/quranchain1/darhealth-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darhealth-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darhealth-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarMedia Bot ──────────────────────────────────────────
    {
      name: "darmedia-bot",
      cwd: "/workspaces/quranchain1/darmedia-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darmedia-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darmedia-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarRealty Bot ─────────────────────────────────────────
    {
      name: "darrealty-bot",
      cwd: "/workspaces/quranchain1/darrealty-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darrealty-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darrealty-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarCommerce Bot ───────────────────────────────────────
    {
      name: "darcommerce-bot",
      cwd: "/workspaces/quranchain1/darcommerce-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darcommerce-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darcommerce-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarTrade Bot ──────────────────────────────────────────
    {
      name: "dartrade-bot",
      cwd: "/workspaces/quranchain1/dartrade-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/dartrade-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/dartrade-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarEdu Bot ────────────────────────────────────────────
    {
      name: "daredu-bot",
      cwd: "/workspaces/quranchain1/daredu-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/daredu-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/daredu-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarEnergy Bot ─────────────────────────────────────────
    {
      name: "darenergy-bot",
      cwd: "/workspaces/quranchain1/darenergy-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darenergy-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darenergy-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarSecurity Bot ───────────────────────────────────────
    {
      name: "darsecurity-bot",
      cwd: "/workspaces/quranchain1/darsecurity-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darsecurity-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darsecurity-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarTransport Bot ──────────────────────────────────────
    {
      name: "dartransport-bot",
      cwd: "/workspaces/quranchain1/dartransport-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/dartransport-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/dartransport-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarTelecom Bot ────────────────────────────────────────
    {
      name: "dartelecom-bot",
      cwd: "/workspaces/quranchain1/dartelecom-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/dartelecom-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/dartelecom-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── Omar AI Control Plane Bot ─────────────────────────────
    {
      name: "omarai-bot",
      cwd: "/workspaces/quranchain1/omarai-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/omarai-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/omarai-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarDeFi Bot ───────────────────────────────────────────
    {
      name: "dardefi-bot",
      cwd: "/workspaces/quranchain1/dardefi-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/dardefi-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/dardefi-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },

    // ── DarHR Bot ─────────────────────────────────────────────
    {
      name: "darhr-bot",
      cwd: "/workspaces/quranchain1/darhr-bot",
      script: "bot.js",
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      min_uptime: 10000,
      watch: ["bot.js"],
      watch_delay: 2000,
      ignore_watch: ["node_modules", "*.log"],
      env: { NODE_ENV: "production" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/workspaces/quranchain1/logs/darhr-bot-error.log",
      out_file: "/workspaces/quranchain1/logs/darhr-bot-out.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },
  ],
};
