mcc: 999
mnc: 70
gnbSearchList:
  - amf

gnbId: 1
idLength: 32
tac: 1

linkIp: 0.0.0.0
ngapIp: 0.0.0.0
gtpIp: 0.0.0.0

amfConfigs:
  - address: amf
    port: 38412

slices:
  - sst: 1
    sd: 0x000001

ignoreStreamIds: true
