// Blog router — serves blog content from generated HTML files
// Blog posts are generated by generate-blog-posts.js and stored in landing-pages/blog/
// This module constructs a blog landing page module for subdomain routing
// and provides path-based /blog/* handling for the main app

import { Hono } from "hono";

// Import manifest of all blog posts (generated by generate-blog-posts.js)
import { blogManifest, type BlogEntry } from "./blogManifest";

// ── Ad Monetization Script (Google AdSense ready) ──
// To activate: Replace YOUR_PUB_ID with your AdSense publisher ID (e.g. ca-pub-1234567890)
// Get yours at https://www.google.com/adsense/
const ADSENSE_PUB_ID = 'ca-pub-XXXXXXXXXX'; // ← Replace with your AdSense pub ID
const ADSENSE_SLOT_ID = '1234567890';        // ← Replace with your ad slot ID

const AD_SCRIPT = `
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_PUB_ID}" crossorigin="anonymous"><` + `/script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  if ('${ADSENSE_PUB_ID}'.includes('XXXXXXXXXX')) return;
  document.querySelectorAll('.ad-unit').forEach(function(el) {
    if (el.dataset.loaded) return;
    el.dataset.loaded = '1';
    var ins = document.createElement('ins');
    ins.className = 'adsbygoogle';
    ins.style.display = 'block';
    ins.dataset.adClient = '${ADSENSE_PUB_ID}';
    ins.dataset.adSlot = '${ADSENSE_SLOT_ID}';
    ins.dataset.adFormat = 'auto';
    ins.dataset.fullWidthResponsive = 'true';
    el.innerHTML = '';
    el.appendChild(ins);
    try { (window.adsbygoogle = window.adsbygoogle || []).push({}); } catch(e) {}
  });
});
<` + `/script>`;

// ── SEO Analytics + Conversion Tracking Script ──
const ANALYTICS_SCRIPT = `
<script>
(function(w,d){
  var p=w.location.pathname,r=d.referrer,t=Date.now();
  var img=new Image();
  img.src='https://darcloud.host/api/analytics/pageview?p='+encodeURIComponent(p)+'&r='+encodeURIComponent(r)+'&t='+t;
})(window,document);
document.addEventListener('click',function(e){
  var a=e.target.closest('a[href*="/checkout/"]');
  if(a){
    var img=new Image();
    img.src='https://darcloud.host/api/analytics/pageview?p='+encodeURIComponent('cta:'+a.href)+'&r='+encodeURIComponent(window.location.pathname)+'&t='+Date.now();
  }
});
<` + `/script>`;

// ── Lead Capture Form (Email Signup) ──
const LEAD_CAPTURE_FORM = `
<div class="lead-capture" id="leadCapture">
  <h3>📬 Get Halal Tech Insights Weekly</h3>
  <p>Join 10,000+ Muslims building with ethical technology. Free newsletter — no spam, no riba.</p>
  <form id="leadForm" onsubmit="return submitLead(event)">
    <div style="display:flex;gap:.5rem;flex-wrap:wrap;justify-content:center">
      <input type="email" id="leadEmail" placeholder="your@email.com" required
        style="padding:.6rem 1rem;border-radius:8px;border:1px solid #21262d;background:#0d1117;color:#e6edf3;font-size:.9rem;min-width:220px">
      <button type="submit" style="padding:.6rem 1.5rem;border-radius:8px;border:none;font-weight:700;background:linear-gradient(135deg,#00d4ff,#10b981);color:#000;cursor:pointer;font-size:.9rem">Subscribe Free →</button>
    </div>
    <p id="leadMsg" style="margin-top:.5rem;font-size:.8rem;color:#8b949e"></p>
  </form>
</div>
<script>
function submitLead(e){
  e.preventDefault();
  var email=document.getElementById('leadEmail').value;
  var msg=document.getElementById('leadMsg');
  msg.textContent='Subscribing...';
  fetch('https://darcloud.host/api/leads/subscribe',{
    method:'POST',
    headers:{'Content-Type':'application/json'},
    body:JSON.stringify({email:email,source:'blog',page:window.location.pathname})
  }).then(function(r){return r.json()}).then(function(d){
    if(d.success){
      msg.style.color='#10b981';
      msg.textContent='Subscribed! Check your inbox.';
      document.getElementById('leadForm').style.display='none';
      var img=new Image();
      img.src='https://darcloud.host/api/analytics/pageview?p='+encodeURIComponent('lead:'+email.split('@')[1])+'&r='+encodeURIComponent(window.location.pathname)+'&t='+Date.now();
    } else {
      msg.style.color='#f59e0b';
      msg.textContent=d.error||'Please try again.';
    }
  }).catch(function(){msg.style.color='#f59e0b';msg.textContent='Network error. Try again.';});
  return false;
}
<` + `/script>`;

// ── Brand constants ──
const BRAND = {
  bg: '#07090f', s1: '#0d1117', s2: '#161b22', bdr: '#21262d',
  cyan: '#00d4ff', emerald: '#10b981', gold: '#f59e0b', purple: '#8b5cf6',
  txt: '#e6edf3', muted: '#8b949e',
};

const manifest: BlogEntry[] = blogManifest;

// ── Inline blog index page for blog.darcloud.host ──
function blogIndexHTML(): string {
  const catCounts: Record<string, number> = {};
  for (const entry of manifest) {
    catCounts[entry.cat] = (catCounts[entry.cat] || 0) + 1;
  }

  const catCards = Object.entries(catCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([cat, count]) =>
      `<a class="cat-card" href="/blog/category/${cat}">${cat.replace(/-/g, ' ')} <span>(${count})</span></a>`
    ).join('\n');

  const latestLinks = manifest.slice(0, 20).map(e =>
    `<a class="post-link" href="/blog/${e.slug}">${e.title}</a>`
  ).join('\n');

  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DarCloud Blog — Islamic Tech, AI, Blockchain & Halal Economy</title>
<meta name="description" content="Expert articles on Islamic finance, blockchain, AI, mesh networking, and the $2.7 trillion halal economy.">
<meta name="robots" content="index,follow">
<link rel="canonical" href="https://darcloud.host/blog">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>☁️</text></svg>">
<style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;background:${BRAND.bg};color:${BRAND.txt}}
a{color:${BRAND.cyan};text-decoration:none}a:hover{text-decoration:underline}
nav{position:sticky;top:0;z-index:100;background:rgba(7,9,15,.92);backdrop-filter:blur(12px);border-bottom:1px solid ${BRAND.bdr};padding:.75rem 2rem;display:flex;justify-content:space-between;align-items:center}
.logo{font-size:1.3rem;font-weight:700;background:linear-gradient(135deg,${BRAND.cyan},${BRAND.emerald});-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.hero{text-align:center;padding:4rem 1.5rem}
.hero h1{font-size:2.5rem;font-weight:800;margin-bottom:1rem}
.hero h1 span{background:linear-gradient(135deg,${BRAND.cyan},${BRAND.emerald});-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.hero p{color:${BRAND.muted};font-size:1.1rem}
.stats{text-align:center;color:${BRAND.muted};padding:1rem;font-size:.9rem}
.cats{display:flex;flex-wrap:wrap;gap:.6rem;justify-content:center;max-width:900px;margin:2rem auto;padding:0 1rem}
.cat-card{padding:.5rem 1rem;background:${BRAND.s1};border:1px solid ${BRAND.bdr};border-radius:8px;font-size:.85rem;text-transform:capitalize;transition:all .2s}
.cat-card:hover{border-color:${BRAND.cyan};transform:translateY(-2px);text-decoration:none}
.cat-card span{color:${BRAND.muted};font-size:.75rem}
h2{text-align:center;margin:3rem 0 1.5rem;font-size:1.5rem}
.posts{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1rem;max-width:1100px;margin:0 auto;padding:0 1.5rem 3rem}
.post-link{padding:1rem;background:${BRAND.s1};border:1px solid ${BRAND.bdr};border-radius:10px;text-transform:capitalize;font-size:.9rem;transition:all .2s}
.post-link:hover{border-color:${BRAND.cyan};transform:translateY(-2px);text-decoration:none}
.lead-capture{background:linear-gradient(135deg,${BRAND.s1},${BRAND.s2});border:1px solid ${BRAND.cyan}33;border-radius:12px;padding:2rem;text-align:center;margin:2.5rem auto;max-width:600px}
.lead-capture h3{margin-bottom:.5rem;font-size:1.2rem}.lead-capture p{color:${BRAND.muted};font-size:.9rem;margin-bottom:1rem}
footer{padding:2rem;border-top:1px solid ${BRAND.bdr};text-align:center;color:${BRAND.muted};font-size:.8rem}
</style>
</head><body>
<nav><a class="logo" href="https://darcloud.host">☁️ DarCloud Blog</a></nav>
<div class="hero"><h1>The <span>DarCloud</span> Blog</h1><p>Deep dives into Islamic tech, blockchain, AI, and the $2.7T halal economy.</p></div>
<p class="stats">📝 ${manifest.length} articles across ${Object.keys(catCounts).length} categories</p>
<div class="cats">${catCards}</div>
<h2>Latest Articles</h2>
<div class="posts">${latestLinks}</div>
${LEAD_CAPTURE_FORM}
<footer>© 2026 DarCloud Empire. All rights reserved.</footer>
${AD_SCRIPT}
${ANALYTICS_SCRIPT}
</body></html>`;
}

// ── Category page ──
function categoryPageHTML(catSlug: string): string {
  const posts = manifest.filter(e => e.cat === catSlug);
  const catName = catSlug.replace(/-/g, ' ');
  const links = posts.map(e =>
    `<a class="post-link" href="/blog/${e.slug}">${e.title}</a>`
  ).join('\n');

  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${catName} Articles | DarCloud Blog</title>
<meta name="description" content="All articles about ${catName} — Islamic tech insights from DarCloud.">
<link rel="canonical" href="https://darcloud.host/blog/category/${catSlug}">
<style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;background:${BRAND.bg};color:${BRAND.txt}}
a{color:${BRAND.cyan};text-decoration:none}a:hover{text-decoration:underline}
nav{position:sticky;top:0;z-index:100;background:rgba(7,9,15,.92);backdrop-filter:blur(12px);border-bottom:1px solid ${BRAND.bdr};padding:.75rem 2rem;display:flex;justify-content:space-between;align-items:center}
.logo{font-size:1.3rem;font-weight:700;background:linear-gradient(135deg,${BRAND.cyan},${BRAND.emerald});-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.hero{text-align:center;padding:3rem 1.5rem}
.hero h1{font-size:2rem;font-weight:800;text-transform:capitalize;margin-bottom:.5rem}
.hero p{color:${BRAND.muted}}
.posts{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1rem;max-width:1100px;margin:2rem auto;padding:0 1.5rem 3rem}
.post-link{padding:1rem;background:${BRAND.s1};border:1px solid ${BRAND.bdr};border-radius:10px;text-transform:capitalize;font-size:.9rem;transition:all .2s}
.post-link:hover{border-color:${BRAND.cyan};transform:translateY(-2px);text-decoration:none}
.back{text-align:center;padding:1rem;font-size:.85rem}
footer{padding:2rem;border-top:1px solid ${BRAND.bdr};text-align:center;color:${BRAND.muted};font-size:.8rem}
</style>
</head><body>
<nav><a class="logo" href="https://darcloud.host">☁️ DarCloud Blog</a></nav>
<div class="hero"><h1>${catName}</h1><p>${posts.length} articles</p></div>
<p class="back"><a href="/blog">← Back to all categories</a></p>
<div class="posts">${links}</div>
<footer>© 2026 DarCloud Empire. All rights reserved.</footer>
${ANALYTICS_SCRIPT}
</body></html>`;
}

// ── 404 Page ──
function notFoundHTML(): string {
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Article Not Found | DarCloud Blog</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;background:${BRAND.bg};color:${BRAND.txt};display:flex;align-items:center;justify-content:center;min-height:100vh;text-align:center}
a{color:${BRAND.cyan}}h1{font-size:3rem;margin-bottom:1rem}p{color:${BRAND.muted};margin-bottom:1.5rem}
</style>
</head><body><div><h1>404</h1><p>Article not found.</p><a href="/blog">← Browse all articles</a></div></body></html>`;
}

// ── Hono sub-app for /blog/* routes ──
export const blogRouter = new Hono<{ Bindings: Env }>();

// Blog index
blogRouter.get("/", (c) => {
  return c.html(blogIndexHTML());
});

// Sitemap
blogRouter.get("/sitemap.xml", async (c) => {
  const urls = manifest.map(e =>
    `  <url><loc>https://darcloud.host/blog/${e.slug}</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>`
  ).join('\n');
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>https://darcloud.host/blog</loc><changefreq>daily</changefreq><priority>0.9</priority></url>
${urls}
</urlset>`;
  return new Response(xml, {
    headers: { "Content-Type": "application/xml", "Cache-Control": "public, max-age=3600" },
  });
});

// RSS Feed
blogRouter.get("/feed.xml", (c) => {
  const items = manifest.slice(0, 50).map(e =>
    `    <item>
      <title>${e.slug.replace(/-/g, ' ')}</title>
      <link>https://darcloud.host/blog/${e.slug}</link>
      <guid>https://darcloud.host/blog/${e.slug}</guid>
    </item>`
  ).join('\n');
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>DarCloud Blog</title>
    <link>https://darcloud.host/blog</link>
    <description>Islamic Tech, AI, Blockchain &amp; Halal Economy</description>
${items}
  </channel>
</rss>`;
  return new Response(xml, {
    headers: { "Content-Type": "application/rss+xml", "Cache-Control": "public, max-age=3600" },
  });
});

// Category page
blogRouter.get("/category/:cat", (c) => {
  const cat = c.req.param("cat");
  const exists = manifest.some(e => e.cat === cat);
  if (!exists) {
    return c.html(notFoundHTML(), 404);
  }
  return c.html(categoryPageHTML(cat));
});

// Individual blog post — serve inline-generated content
blogRouter.get("/:slug", (c) => {
  const slug = c.req.param("slug");
  if (!/^[a-z0-9-]+$/.test(slug)) {
    return c.html(notFoundHTML(), 404);
  }
  const entry = manifest.find(e => e.slug === slug);
  if (!entry) {
    return c.html(notFoundHTML(), 404);
  }
  return c.html(generateInlinePost(entry));
});

// Generate inline blog post
function generateInlinePost(entry: BlogEntry): string {
  const title = entry.title;
  const catName = entry.catName;
  const desc = entry.desc;
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title} | DarCloud Blog</title>
<meta name="description" content="${desc}">
<meta name="keywords" content="${catName}, DarCloud, halal tech, Islamic technology, ${entry.cat.replace(/-/g, ', ')}">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${desc}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="DarCloud Blog">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://darcloud.host/blog/${entry.slug}">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>☁️</text></svg>">
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"Article","headline":"${title.replace(/"/g, '\\"')}","description":"${desc.replace(/"/g, '\\"')}","author":{"@type":"Organization","name":"DarCloud","url":"https://darcloud.host"},"publisher":{"@type":"Organization","name":"DarCloud"},"mainEntityOfPage":"https://darcloud.host/blog/${entry.slug}"}
<` + `/script>
<style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;background:${BRAND.bg};color:${BRAND.txt}}
a{color:${BRAND.cyan};text-decoration:none}a:hover{text-decoration:underline}
nav{position:sticky;top:0;z-index:100;background:rgba(7,9,15,.92);backdrop-filter:blur(12px);border-bottom:1px solid ${BRAND.bdr};padding:.75rem 2rem;display:flex;justify-content:space-between;align-items:center}
.logo{font-size:1.3rem;font-weight:700;background:linear-gradient(135deg,${BRAND.cyan},${BRAND.emerald});-webkit-background-clip:text;-webkit-text-fill-color:transparent}
article{max-width:800px;margin:0 auto;padding:3rem 1.5rem}
article h1{font-size:2rem;font-weight:800;text-transform:capitalize;margin-bottom:1rem}
.meta{color:${BRAND.muted};font-size:.85rem;margin-bottom:2rem;text-transform:capitalize}
article p{color:${BRAND.muted};font-size:1.05rem;line-height:1.8;margin-bottom:1.5rem}
article h2{font-size:1.4rem;font-weight:700;margin:2rem 0 1rem}
.cta{background:linear-gradient(135deg,${BRAND.s1},${BRAND.s2});border:1px solid ${BRAND.cyan}33;border-radius:12px;padding:2rem;text-align:center;margin:2.5rem 0}
.cta h3{margin-bottom:.5rem}.cta p{color:${BRAND.muted};margin-bottom:1rem;font-size:.9rem}
.btn{display:inline-block;padding:.6rem 1.5rem;border-radius:8px;font-weight:600;background:linear-gradient(135deg,${BRAND.cyan},${BRAND.emerald});color:#000}
.ad-unit{background:${BRAND.s1};border:1px solid ${BRAND.bdr};border-radius:10px;padding:1.5rem;text-align:center;margin:2rem 0;min-height:90px}
.lead-capture{background:linear-gradient(135deg,${BRAND.s1},${BRAND.s2});border:1px solid ${BRAND.cyan}33;border-radius:12px;padding:2rem;text-align:center;margin:2.5rem 0}
.lead-capture h3{margin-bottom:.5rem;font-size:1.2rem}.lead-capture p{color:${BRAND.muted};font-size:.9rem;margin-bottom:1rem}
footer{padding:2rem;border-top:1px solid ${BRAND.bdr};text-align:center;color:${BRAND.muted};font-size:.8rem;margin-top:3rem}
</style>
</head><body>
<nav><a class="logo" href="https://darcloud.host">☁️ DarCloud Blog</a></nav>
<article>
  <h1>${title}</h1>
  <div class="meta">📁 ${catName} · ⏱️ 6 min read · 📅 2026</div>
  <p><strong>${catName}</strong> represents one of the fastest-growing sectors in the global halal economy. With the Islamic tech market projected to exceed $2.7 trillion, understanding ${title} is essential for anyone looking to participate in this transformative space.</p>

  <div class="ad-unit"><span style="color:${BRAND.muted};font-size:.7rem">ADVERTISEMENT</span></div>

  <h2>Understanding the Fundamentals</h2>
  <p>At its core, ${title} connects to DarCloud's mission of building sovereign, Shariah-compliant technology infrastructure. Our approach is rooted in Islamic principles — zero riba, full transparency, and fair distribution through the 30/40/10/18/2 revenue split coded into QuranChain's 47-network blockchain.</p>

  <h2>Why This Matters for the Ummah</h2>
  <p>With 2 billion Muslims worldwide, the demand for ethical technology solutions is growing exponentially. DarCloud's ecosystem of 22 Discord bots, 66 AI agents, 72 database tables, and 340,000+ mesh nodes provides the infrastructure to serve this massive market.</p>

  <h2>Technical Implementation</h2>
  <p>Our platform runs on Cloudflare Workers at the edge, backed by D1 database with SQLite, secured with JWT authentication (HMAC-SHA256) and PBKDF2 password hashing. The entire stack is optimized for global performance while maintaining complete Shariah compliance.</p>

  <div class="ad-unit"><span style="color:${BRAND.muted};font-size:.7rem">ADVERTISEMENT</span></div>

  <h2>Getting Started</h2>
  <p>Jump in with our Pro plan at $49/month for full API access, AI agent integration, and mesh network connectivity. Enterprise customers ($499/month) get white-label capabilities and dedicated infrastructure.</p>

  <div class="cta">
    <h3>🚀 Build on DarCloud</h3>
    <p>Join the 101-company Islamic tech ecosystem.</p>
    <a class="btn" href="https://darcloud.host/checkout/pro">Start Free Trial →</a>
  </div>

  ${LEAD_CAPTURE_FORM}
</article>
<footer>© 2026 DarCloud Empire. All rights reserved.</footer>
${AD_SCRIPT}
${ANALYTICS_SCRIPT}
</body></html>`;
}

// ── Blog subdomain handler (blog.darcloud.host) ──
export const blogSubdomainPage = {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204 });
    }

    if (path === "/health") {
      return Response.json({ status: "healthy", service: "blog", posts: manifest.length });
    }

    if (path === "/sitemap.xml") {
      const urls = manifest.map(e =>
        `  <url><loc>https://blog.darcloud.host/${e.slug}</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>`
      ).join('\n');
      return new Response(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>https://blog.darcloud.host/</loc><changefreq>daily</changefreq><priority>1.0</priority></url>
${urls}
</urlset>`, { headers: { "Content-Type": "application/xml" } });
    }

    const catMatch = path.match(/^\/category\/([a-z0-9-]+)\/?$/);
    if (catMatch) {
      const exists = manifest.some(e => e.cat === catMatch[1]);
      if (exists) {
        return new Response(categoryPageHTML(catMatch[1]), {
          headers: { "Content-Type": "text/html;charset=utf-8" },
        });
      }
    }

    const slugMatch = path.match(/^\/([a-z0-9-]+)\/?$/);
    if (slugMatch && slugMatch[1] !== 'favicon.ico') {
      const entry = manifest.find(e => e.slug === slugMatch[1]);
      if (entry) {
        return new Response(generateInlinePost(entry), {
          headers: { "Content-Type": "text/html;charset=utf-8" },
        });
      }
    }

    return new Response(blogIndexHTML(), {
      headers: { "Content-Type": "text/html;charset=utf-8" },
    });
  }
};
